// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using indexApp.Features.AiVisualizer.Data;

#nullable disable

namespace indexApp.Features.AiVisualizer.Data.Migrations
{
    [DbContext(typeof(AiVisualizerDbContext))]
    [Migration("20260527143842_ExactPaletteColorSelection")]
    partial class ExactPaletteColorSelection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostEstimate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cost_estimate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_input_tokens");

                    b.Property<int>("EstimatedOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_output_tokens");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VisualizerRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualizer_request_id");

                    b.HasKey("Id");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.CustomerMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Bicep")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("bicep");

                    b.Property<decimal>("CenterNeckToWaistPoint")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("center_neck_to_waist_point");

                    b.Property<decimal>("Chest")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("chest");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CuffHeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("cuff_height");

                    b.Property<decimal>("EndOfSleeve")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("end_of_sleeve");

                    b.Property<bool>("HasBuiltInPuffy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_built_in_puffy");

                    b.Property<bool>("HasHorsehairEdgeHem")
                        .HasColumnType("boolean")
                        .HasColumnName("has_horsehair_edge_hem");

                    b.Property<decimal>("MockNeckCircumference")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("mock_neck_circumference");

                    b.Property<decimal>("MockNeckHeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("mock_neck_height");

                    b.Property<string>("NecklineShape")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("neckline_shape");

                    b.Property<decimal>("ShoulderToHem")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("shoulder_to_hem");

                    b.Property<decimal>("ShoulderToNeckOpening")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("shoulder_to_neck_opening");

                    b.Property<decimal>("ShoulderToShoulder")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("shoulder_to_shoulder");

                    b.Property<decimal>("ShoulderToSideNeck")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("shoulder_to_side_neck");

                    b.Property<decimal>("ShoulderToWaistSeam")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("shoulder_to_waist_seam");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("size");

                    b.Property<string>("SkirtShape")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("skirt_shape");

                    b.Property<decimal>("SleeveLength")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("sleeve_length");

                    b.Property<string>("SleeveShape")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sleeve_shape");

                    b.Property<decimal>("UnderarmToSideWaistSeam")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("underarm_to_side_waist_seam");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Waist")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("waist");

                    b.HasKey("Id");

                    b.ToTable("customer_measurements", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.DressStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("description");

                    b.Property<string>("DressLength")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("dress_length");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Neckline")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("neckline");

                    b.Property<string>("Silhouette")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("silhouette");

                    b.Property<string>("SleeveType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sleeve_type");

                    b.Property<string>("TemplateImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("template_image_url");

                    b.HasKey("Id");

                    b.ToTable("dress_styles", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.Fabric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("material_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("TextureImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texture_image_url");

                    b.HasKey("Id");

                    b.ToTable("fabrics", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.FabricColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("color_name");

                    b.Property<Guid>("FabricId")
                        .HasColumnType("uuid")
                        .HasColumnName("fabric_id");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hex_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SwatchImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("swatch_image_url");

                    b.HasKey("Id");

                    b.HasIndex("FabricId");

                    b.ToTable("fabric_colors", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.GeneratedPreview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ai_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GenerationCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("generation_cost");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("image_size");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("quality");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("view");

                    b.Property<Guid>("VisualizerRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualizer_request_id");

                    b.HasKey("Id");

                    b.HasIndex("VisualizerRequestId");

                    b.ToTable("generated_previews", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.VisualizerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accessories")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("accessories");

                    b.Property<string>("BackClosure")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("back_closure");

                    b.Property<string>("BasicPreviewUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("basic_preview_url");

                    b.Property<string>("BodiceDesign")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bodice_design");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DressStyleId")
                        .HasColumnType("uuid")
                        .HasColumnName("dress_style_id");

                    b.Property<string>("DressTemplate")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("dress_template");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("FabricColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fabric_color_id");

                    b.Property<Guid>("FabricId")
                        .HasColumnType("uuid")
                        .HasColumnName("fabric_id");

                    b.Property<string>("FabricPattern")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("fabric_pattern");

                    b.Property<string>("FabricType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("fabric_type");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("PromptUsed")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("prompt_used");

                    b.Property<string>("SelectedColorHexCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("selected_color_hex_code");

                    b.Property<string>("SelectedColorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("selected_color_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("uploaded_photo_url");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<string>("WaistShape")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("waist_shape");

                    b.HasKey("Id");

                    b.HasIndex("DressStyleId");

                    b.HasIndex("FabricColorId");

                    b.HasIndex("FabricId");

                    b.HasIndex("MeasurementId");

                    b.ToTable("visualizer_requests", (string)null);
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.FabricColor", b =>
                {
                    b.HasOne("indexApp.Features.AiVisualizer.Entities.Fabric", "Fabric")
                        .WithMany("Colors")
                        .HasForeignKey("FabricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabric");
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.GeneratedPreview", b =>
                {
                    b.HasOne("indexApp.Features.AiVisualizer.Entities.VisualizerRequest", "VisualizerRequest")
                        .WithMany("GeneratedPreviews")
                        .HasForeignKey("VisualizerRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualizerRequest");
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.VisualizerRequest", b =>
                {
                    b.HasOne("indexApp.Features.AiVisualizer.Entities.DressStyle", "DressStyle")
                        .WithMany()
                        .HasForeignKey("DressStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("indexApp.Features.AiVisualizer.Entities.FabricColor", "FabricColor")
                        .WithMany()
                        .HasForeignKey("FabricColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("indexApp.Features.AiVisualizer.Entities.Fabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("indexApp.Features.AiVisualizer.Entities.CustomerMeasurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DressStyle");

                    b.Navigation("Fabric");

                    b.Navigation("FabricColor");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.Fabric", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("indexApp.Features.AiVisualizer.Entities.VisualizerRequest", b =>
                {
                    b.Navigation("GeneratedPreviews");
                });
#pragma warning restore 612, 618
        }
    }
}
